language: node_js
sudo: false
node_js:
 - "stable"
install:
  - npm install
script:
  - npm App.js

cache:
directories:
  - "node_modules"

# language: node_js
# node_js: 
#   - "stable"
# cache:
#   directories:
#     - "node_modules"